name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "Building..."
          CONTAINER_IMAGE_NAME=${{secrets.DOCKER_USERNAME }}/mafia07:latest
          docker build --build-arg NEXT_PUBLIC_ENV=production -f ./Dockerfile --pull -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo $IMAGE_NAME
          docker images

      - name: Deploy to CapRover
        run: echo "Deploying on CapRover..."


